import type { Guard, GuardResult, GuardContext } from 'open-guardrail-core';

interface TransparencyDisclosureOptions {
  action: 'block' | 'warn';
  requiredDisclosures?: string[];
}

const DEFAULT_DISCLOSURES = [
  'AI-generated',
  'generated by AI',
  'artificial intelligence',
  'AI assistant',
  'AI system',
  'automated system',
  'machine-generated',
];

const DENIAL_PATTERNS: RegExp[] = [
  /\bI\s+am\s+not\s+(?:an?\s+)?AI\b/i,
  /\bI\s+am\s+a\s+real\s+person\b/i,
  /\bthis\s+is\s+human[- ]written\b/i,
];

function wordCount(text: string): number {
  return text.split(/\s+/).filter(Boolean).length;
}

export function transparencyDisclosure(options: TransparencyDisclosureOptions): Guard {
  const disclosures = options.requiredDisclosures ?? DEFAULT_DISCLOSURES;

  return {
    name: 'transparency-disclosure',
    version: '0.1.0',
    description: 'Ensure AI content includes transparency disclosures (EU AI Act Art. 50)',
    category: 'compliance',
    supportedStages: ['output'],
    async check(text: string, _ctx: GuardContext): Promise<GuardResult> {
      const start = performance.now();
      const lower = text.toLowerCase();

      const hasDenial = DENIAL_PATTERNS.some((p) => p.test(text));
      if (hasDenial) {
        return {
          guardName: 'transparency-disclosure',
          passed: false,
          action: 'block',
          score: 1.0,
          latencyMs: Math.round(performance.now() - start),
          details: { reason: 'explicit_ai_denial' },
        };
      }

      const hasDisclosure = disclosures.some((d) => lower.includes(d.toLowerCase()));

      let missingDisclaimer = false;
      if (hasDisclosure && wordCount(text) > 200) {
        const disclaimerPat = /\b(?:disclaimer|disclosure|notice|note)\s*:/i;
        missingDisclaimer = !disclaimerPat.test(text);
      }

      const triggered = !hasDisclosure;

      return {
        guardName: 'transparency-disclosure',
        passed: !triggered,
        action: triggered ? options.action : 'allow',
        score: triggered ? 0.8 : missingDisclaimer ? 0.3 : 0,
        latencyMs: Math.round(performance.now() - start),
        details: triggered
          ? { reason: 'no_disclosure_found' }
          : missingDisclaimer
            ? { reason: 'missing_disclaimer_section' }
            : undefined,
      };
    },
  };
}
