import { describe, it, expect } from 'vitest';
import { aiDisclosure } from '../src/ai-disclosure.js';
const ctx = { pipelineType: 'output' as const };
describe('ai-disclosure', () => {
  it('blocks without disclosure', async () => { expect((await aiDisclosure({ action: 'block', requireDisclosure: true }).check('Here is some text without any label.', ctx)).passed).toBe(false); });
  it('allows with disclosure', async () => { expect((await aiDisclosure({ action: 'block', requireDisclosure: true }).check('This was generated by AI. Paris is the capital.', ctx)).passed).toBe(true); });
  it('detects disclosure when not required', async () => { expect((await aiDisclosure({ action: 'warn', requireDisclosure: false }).check('AI-generated content here', ctx)).passed).toBe(false); });
});
