"""Ensure AI content includes transparency disclosures (EU AI Act Art. 50)."""
from __future__ import annotations

import re
import time
from typing import List, Optional

from open_guardrail.core import GuardResult

_DEFAULT_DISCLOSURES = [
    "AI-generated",
    "generated by AI",
    "artificial intelligence",
    "AI assistant",
    "AI system",
    "automated system",
    "machine-generated",
]

_DENIAL: list[re.Pattern[str]] = [
    re.compile(
        r"\bI\s+am\s+not\s+(?:an?\s+)?AI\b",
        re.IGNORECASE,
    ),
    re.compile(
        r"\bI\s+am\s+a\s+real\s+person\b",
        re.IGNORECASE,
    ),
    re.compile(
        r"\bthis\s+is\s+human[- ]written\b",
        re.IGNORECASE,
    ),
]

_DISCLAIMER = re.compile(
    r"\b(?:disclaimer|disclosure|notice|note)\s*:",
    re.IGNORECASE,
)


class _TransparencyDisclosure:
    def __init__(
        self,
        *,
        action: str = "warn",
        required_disclosures: Optional[List[str]] = None,
    ) -> None:
        self.name = "transparency-disclosure"
        self.action = action
        self._disclosures = (
            required_disclosures or _DEFAULT_DISCLOSURES
        )

    def check(
        self, text: str, stage: str = "output"
    ) -> GuardResult:
        start = time.perf_counter()
        lower = text.lower()

        has_denial = any(p.search(text) for p in _DENIAL)
        if has_denial:
            elapsed = (
                time.perf_counter() - start
            ) * 1000
            return GuardResult(
                guard_name="transparency-disclosure",
                passed=False,
                action="block",
                score=1.0,
                message="Explicit AI denial detected",
                latency_ms=round(elapsed, 2),
                details={"reason": "explicit_ai_denial"},
            )

        has_disc = any(
            d.lower() in lower for d in self._disclosures
        )

        missing_disclaimer = False
        if has_disc and len(text.split()) > 200:
            missing_disclaimer = not _DISCLAIMER.search(
                text
            )

        triggered = not has_disc
        elapsed = (time.perf_counter() - start) * 1000

        return GuardResult(
            guard_name="transparency-disclosure",
            passed=not triggered,
            action=(
                self.action if triggered else "allow"
            ),
            score=(
                0.8
                if triggered
                else 0.3 if missing_disclaimer else 0.0
            ),
            message=(
                "No disclosure found"
                if triggered
                else (
                    "Missing disclaimer section"
                    if missing_disclaimer
                    else None
                )
            ),
            latency_ms=round(elapsed, 2),
            details=(
                {"reason": "no_disclosure_found"}
                if triggered
                else (
                    {
                        "reason": "missing_disclaimer_section"
                    }
                    if missing_disclaimer
                    else None
                )
            ),
        )


def transparency_disclosure(
    *,
    action: str = "warn",
    required_disclosures: Optional[List[str]] = None,
) -> _TransparencyDisclosure:
    return _TransparencyDisclosure(
        action=action,
        required_disclosures=required_disclosures,
    )
